apiVersion: apps/v1
kind: Deployment
metadata:
  name: credentials-store-app
  labels:
    app: credentials-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credentials-store
  template:
    metadata:
      labels:
        app: credentials-store
    spec:
      containers:
      - name: credentials-store
        image: mmirzabaig/credentials-store:v13
        env:
        - name: MONGODB_URI
          value: m-o-n-g-o-d-b-i-p
        ports:
        - containerPort: 6680
